[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
name = "compiler_builtins"
version = "0.0.0"

[lib]
name = "compiler_builtins"
path = "lib.rs"

[build-dependencies]
gcc = "0.3.27"
rustc-cfg = "0.2.0"

[dependencies.core]
optional = true
path = "../libcore"

[dependencies.rlibc]
git = "https://github.com/alexcrichton/rlibc"
optional = true

[dev-dependencies]
quickcheck = "0.3.1"
rand = "0.3.14"
gcc_s = { path = "gcc_s" }
compiler-rt = { path = "compiler-rt" }

[features]
# Build the missing intrinsics from compiler-rt C source code
c = []
# for integration into rust-lang/rust
rustbuild = ["core"]
weak = ["rlibc/weak"]

[workspace]
