[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
name = "compiler_builtins"
version = "0.1.0"

[build-dependencies]
rustc-cfg = { version = "0.3.0", optional = true }

[build-dependencies.gcc]
optional = true
version = "0.3.36"

[dev-dependencies]
quickcheck = "0.3.1"
rand = "0.3.14"
gcc_s = { path = "gcc_s" }
compiler-rt = { path = "compiler-rt" }

[features]
# Build the missing intrinsics from compiler-rt C source code
c = ["gcc", "rustc-cfg"]
# Mark this crate as the #![compiler_builtins] crate
compiler-builtins = []
default = ["compiler-builtins"]
# Include implementations of memory operations like memcpy
mem = []
rustbuild = ["compiler-builtins"]

[workspace]
